### ISSUE TITLE
Configurable Gitlab Endpoint

### ISSUE THREAD

**Issue by kadrach** [leonardokl/gitlab-chrome-extension#17]
We're running an on-prem install of Gitlab CE. I simply updated all endpoints in `src/constants.js` to point to the right endpoint and everything seems to work.

I don't have any experience in JavaScript development, can this be made configurable in the extension itself? :)

**Comment by leonardokl** [comment]
I can make the Gitlab Host configurable.
I'll use the `Settings` options on the user dropdown to do so, actually it's just a link to Gitlab settings page.
Thanks for your feedback.

**Comment by leonardokl** [comment]
I've updated the extension with that feature, it can be accessed on the extension options (Right Click / Options), changing the GitLab URL.
