### ISSUE TITLE
Display nested namespaces

### ISSUE THREAD

**Issue by kadrach** [leonardokl/gitlab-chrome-extension#18]
Gitlab fairly recently introduced the concept of "sub-groups", essentially a nested namespace. 

The extension currently only displays the direct parent group of a repository, e.g.
```
project_name
group
```

While there is some ludicrous limit to nested subgroups (20+), it would be nice to somehow display a little more detail, e.g. 

```
project_name
name_with_namespace ( ... > grandparent > parent > group )
```

**Comment by leonardokl** [comment]
Hello, i didn't know that feature, just checked after your comment.
I saw that GitLab are providing that path on the api and updated the reference.
```js
{
  namespace: {
    full_path: 'grandparent/parent/group'
  }
}
```
Thanks for the recommendation, the new version will be available soon.
